### ISSUE TITLE
Bar Name and Description not working

### ISSUE THREAD

**Issue by zhdenny** [karlomikus/vue-salt-rim#68]
Maybe I'm not understanding how to incorporate these new features......I tried adding this to my .env file and updating. I don't see anything change in the logo. I'm using the docker compose setup.

```
BAR_NAME=MyBar
DESCRIPTION=6PM
```

![image](https://user-images.githubusercontent.com/26662131/227750663-7d1b21a4-7d42-4be0-8cbb-1fc7f8a55faa.png)

**Comment by karlomikus** [comment]
You need to put those variables in `docker-compose.yml` file:

for example:
```yaml
salt-rim:
    image: barassistant/salt-rim:latest
    depends_on:
      - bar-assistant
    environment:
      - API_URL=$API_URL
      - MEILISEARCH_URL=$MEILISEARCH_URL
      - BAR_NAME=Test # or $BAR_NAME to map the variable from .env
      - DESCRIPTION=Description # or $DESCRIPTION to map the variable from .env
    restart: unless-stopped
```
